apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: craig-uw-test-project
  namespace: default
  labels:
    app: craig-uw-test-project
    public-lb: traefik
spec:
  rules:
  - host: craigstestapp.dev.uw.systems
    http:
      paths:
      - path: /
        backend:
          serviceName: craig-uw-test-project
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: craig-uw-test-project
  namespace: default
  labels:
    app: craig-uw-test-project
    public-lb: traefik
spec:
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: craig-uw-test-project
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: craig-uw-test-project
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: craig-uw-test-project
        public-lb: traefik
    spec:
      containers:
        - name: craig-uw-test-project
          image: docker.io/craigtaub/craig-uw-test-project
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
          ports:
           - containerPort: 3000
